language: go

# use containers which run faster and have cache
sudo: false

cache:
  directories:
    $GOPATH/src

go:
  - 1.8.x

go_import_path: github.com/StudentRND/lgtm

script:
  - go build -v github.com/StudentRND/lgtm

notifications:
  email: false
